 
version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=singlestone
      - POSTGRES_USER=singlestone
      - POSTGRES_DB=singlestone
    ports:
      - 5432:5432
    volumes:
      - ./config_pg/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config_pg/students.csv:/tmp/students.csv

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=singlestone
      - MONGO_INITDB_ROOT_USERNAME=singlestone
      - MONGO_INITDB_ROOT_PASSWORD=singlestone
    volumes:
     #  - ./config_mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./config_mongo/teachers.json:/tmp/teachers.json
    command: mongoimport --jsonArray --db test --collection docs --file example2.json

    ports:
      - 27017-27019:27017-27019

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=singlestone
      - ME_CONFIG_MONGODB_ADMINPASSWORD=singlestone
      - ME_CONFIG_BASICAUTH_USERNAME=singlestone
      - ME_CONFIG_BASICAUTH_PASSWORD=singlestone
    depends_on:
          - mongo